### ISSUE TITLE
Example doesn't work?

### ISSUE THREAD

**Issue by akfaew** [qdrant/go-client#26]
Hello,

I'm trying to run the examples/authentication code. I run it as:

```
$ go run . -addr xxxxxxx.us-east-1-0.aws.cloud.qdrant.io:6333
2023/06/07 08:39:51 could not get collections: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 464 (); malformed header: missing HTTP content-type
exit status 1
```

I have manually edited line 35 to contain my API key.

**Comment by generall** [comment]
Hi @akfaew, thanks for reaching out! It seems you are using REST port (6333), while go client works with gRPC port (6334)

Please try runnning the command with `go run . -addr xxxxxxx.us-east-1-0.aws.cloud.qdrant.io:6334`

The expected output should be:

Similar to this:
```
go run examples/authentication/main.go -addr 6eb7695c-e21f-459c-aa8f-9adb06594876.eu-central-1-0.aws.cloud.qdrant.io:6334
2023/06/08 11:41:26 List of collections: [name:"collection-concurrent-lifecycle-drill"]
```
