### ISSUE TITLE
Go API doesn't match with REST API and  better documentation is needed

### ISSUE THREAD

**Issue by mango009** [qdrant/go-client#30]
For example, REST API has a `GetPoint` that get only one single point but Go has only compatible API to get multiple points.

Also, the example does not demonstrate everything that can be done with the go client (success and failure case).  it will help if this repo can provide better documentation such as `GoDoc` or a better `ReadMe`. To find out the API available (function signature, params and result type), I have to go through the `.proto` files and cross checking the generated `.go` files.

**Comment by Anush008** [comment]
Hey. We released a revamp of the SDK.
- Usage examples are available throughout the [Qdrant documentation](https://qdrant.tech/documentation/quick-start/) and [API Reference](https://api.qdrant.tech/).
- [Godoc Reference](https://pkg.go.dev/github.com/qdrant/go-client)
