### ISSUE TITLE
The query conditions are too complex

### ISSUE THREAD

**Issue by shzy2012** [qdrant/go-client#43]
Can it be simplified, such as supporting map?

json format
```json
POST /collections/chatapp/points/delete
{
    "filter": {
        "must": [
            {
                "key": "source",
                "match": {
                    "value": "example.pdf"
                }
            }
        ]
    }
}
```

to ----->

go code
<img width="860" alt="image" src="https://github.com/qdrant/go-client/assets/3347060/6e342b78-9baa-46a6-805d-235c7513d574">

**Comment by shzy2012** [comment]
or 

```go
	filter := map[string]interface{}{
		"filter": map[string]interface{}{
			"must": []map[string]interface{}{
				{
					"key": "source",
				},
				{
					"match": map[string]string{
						"value": "example.pdf",
					},
				},
			},
		},
	}

```

**Comment by Matthieu-Coddity** [comment]
Agreed. I had to recode a Qdrant http client in go, because the GRPC is over complicated, especially on filters management. Qdrant is very great, and for those who dont want to use Langchain go...

**Comment by Anush008** [comment]
Hey. We released a revamp of the SDK that improves this.
Please refer to https://qdrant.tech/documentation/concepts/filtering/#filtering-clauses
