### ISSUE TITLE
malformed header: missing HTTP content-type

### ISSUE THREAD

**Issue by matthiasthomas** [qdrant/go-client#48]
We've been getting the following error 7 times between July 25th and July 30th.
```
failed to upsert in qdrant collection: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 500 (Internal Server Error); malformed header: missing HTTP content-type
```

Our worker automatically retries and it goes through so these are transient errors. But I want to understand where it's coming from.

I asked the question in qdrant's Discord but nothing happened in qdrant cloud on these dates so they think it might be related to the go client.

Any idea where this could be coming from? Ever experienced it before?

**Comment by Anush008** [comment]
Could you try the latest version.
Also, ensure the port is 6334 and not 6333.

**Comment by Anush008** [comment]
Closing since stale.
Feel free to reopen if needed.
