### ISSUE TITLE
Does go-client support serverless vector db?

### ISSUE THREAD

**Issue by skyleaworlder** [qdrant/go-client#56]
I see "Python client allows you to run same code in local mode without running Qdrant server".

I'd like to know if go-client also provides the same functionality.

**Comment by Anush008** [comment]
Hey. The in-memory mode is only supported in the Python SDK.
There are no plans to support it in the others.

**Comment by skyleaworlder** [comment]
> Hey. The in-memory mode is only supported in the Python SDK. There are no plans to support it in the others.

Thank you! Feel sorry to hear that 😢
